Repository VINCENT-ARCHIVE/Vincent-Server, pull requests merged in 2024-09, with the labels that each got.

#84 [Refactor/83] MemberService 코드 수정
  src/main/java/com/vincent/config/redis/repository/RefreshTokenRepository.java
  src/main/java/com/vincent/config/redis/service/RedisService.java
  src/main/java/com/vincent/domain/member/service/MemberService.java
  src/main/java/com/vincent/domain/member/service/data/MemberDataService.java
  src/test/java/com/vincent/config/redis/service/RedisServiceTest.java
  src/test/java/com/vincent/domain/member/service/MemberServiceTest.java
  src/test/java/com/vincent/domain/member/service/data/MemberDataServiceTest.java
Labels: :recycle: refactor

#86 [Hotfix/85] Long -> Integer로 수정
  src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java
  src/main/java/com/vincent/domain/building/converter/BuildingConverter.java
Labels: :fire: hotfix

#89 [Hotfix/88] Repository의 네이티브 쿼리 테이블 명 변경
  src/main/java/com/vincent/domain/building/repository/BuildingRepository.java
Labels: :fire: hotfix

#91 [Fix/90] docker-compose 수정
  .github/workflows/deploy.yml
  docker-compose.yml
Labels: :hammer: fix

#95 [Hotfix/94] 층 정보 조회 api 수정
  .github/workflows/deploy.yml
  src/main/java/com/vincent/domain/building/entity/Space.java
  src/main/java/com/vincent/domain/socket/entity/Socket.java
Labels: :fire: hotfix

#98 [Refactor/92] BookmarkService 리팩토링
  src/main/java/com/vincent/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/vincent/domain/bookmark/service/BookmarkService.java
  src/main/java/com/vincent/domain/bookmark/service/data/BookmarkDataService.java
  src/test/java/com/vincent/domain/bookmark/controller/BookmarkControllerTest.java
  src/test/java/com/vincent/domain/bookmark/service/BookmarkServiceTest.java
  src/test/java/com/vincent/domain/bookmark/service/data/BookmarkDataServiceTest.java
Labels: :recycle: refactor

#100 Refactor/82 Repository 분리
  src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java
  src/main/java/com/vincent/domain/building/converter/BuildingConverter.java
  src/main/java/com/vincent/domain/building/repository/BuildingRepository.java
  src/main/java/com/vincent/domain/building/repository/FloorRepository.java
  src/main/java/com/vincent/domain/building/repository/SpaceRepository.java
  src/main/java/com/vincent/domain/building/repository/custombuilding/CustomBuildingRepository.java
  src/main/java/com/vincent/domain/building/repository/custombuilding/CustomBuildingRepositoryImpl.java
  src/main/java/com/vincent/domain/building/repository/customfloor/CustomFloorRepository.java
  src/main/java/com/vincent/domain/building/repository/customfloor/CustomFloorRepositoryImpl.java
  src/main/java/com/vincent/domain/building/repository/customspace/CustomSpaceRepository.java
  src/main/java/com/vincent/domain/building/repository/customspace/CustomSpaceRepositoryImpl.java
  src/test/java/com/vincent/domain/building/controller/BuildingControllerTest.java
  src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java
Labels: :recycle: refactor

#101 :recycle: BuildingService 리팩토링
  src/main/java/com/vincent/domain/building/service/BuildingService.java
  src/main/java/com/vincent/domain/building/service/data/FloorDataService.java
  src/main/java/com/vincent/domain/building/service/data/SpaceDataService.java
  src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java
  src/test/java/com/vincent/domain/building/service/data/BuildingDataServiceTest.java
  src/test/java/com/vincent/domain/building/service/data/FloorDataServiceTest.java
  src/test/java/com/vincent/domain/building/service/data/SpaceDataServiceTest.java
Labels: :recycle: refactor

#103 :recycle: Socket, Feedback 서비스 리팩토링
  src/main/java/com/vincent/domain/building/repository/FloorRepository.java
  src/main/java/com/vincent/domain/building/service/data/FloorDataService.java
  src/main/java/com/vincent/domain/building/service/data/SpaceDataService.java
  src/main/java/com/vincent/domain/feedback/service/FeedbackService.java
  src/main/java/com/vincent/domain/feedback/service/data/FeedbackDataService.java
  src/main/java/com/vincent/domain/socket/service/SocketService.java
  src/test/java/com/vincent/domain/building/service/data/BuildingDataServiceTest.java
  src/test/java/com/vincent/domain/building/service/data/FloorDataServiceTest.java
  src/test/java/com/vincent/domain/building/service/data/SpaceDataServiceTest.java
  src/test/java/com/vincent/domain/feedback/service/FeedbackServiceTest.java
  src/test/java/com/vincent/domain/feedback/service/data/FeedbackDataServiceTest.java
  src/test/java/com/vincent/domain/socket/service/SocketServiceTest.java
  src/test/java/com/vincent/domain/socket/service/data/SocketDataServiceTest.java
Labels: :recycle: refactor

#106 Hotfix/105 공간 엔티티 이미지 필드 제거
  src/main/java/com/vincent/domain/building/controller/BuildingController.java
  src/main/java/com/vincent/domain/building/entity/Space.java
  src/main/java/com/vincent/domain/building/service/BuildingService.java
  src/test/java/com/vincent/domain/building/controller/BuildingControllerTest.java
  src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java
Labels: :fire: hotfix

#107 :sparkles: 로그 수집 api
  src/main/java/com/vincent/Application.java
  src/main/java/com/vincent/config/aws/s3/S3Service.java
  src/main/java/com/vincent/config/redis/service/RedisService.java
  src/main/java/com/vincent/domain/building/controller/BuildingController.java
  src/main/java/com/vincent/domain/member/controller/MemberController.java
  src/main/java/com/vincent/domain/member/service/MemberService.java
  src/main/java/com/vincent/domain/socket/controller/SocketController.java
  src/main/java/com/vincent/exception/ExceptionAdvice.java
  src/main/java/com/vincent/logging/LoggingFilter.java
  src/main/java/com/vincent/logging/RequestLogInfo.java
  src/main/java/com/vincent/logging/RequestWrapper.java
  src/main/java/com/vincent/logging/ResponseLogInfo.java
  src/main/java/com/vincent/logging/ResponseWrapper.java
  src/main/resources/logback.xml
  src/test/java/com/vincent/aws/S3ServiceTest.java
  src/test/java/com/vincent/config/redis/service/RedisServiceTest.java
  src/test/java/com/vincent/domain/building/controller/BuildingControllerTest.java
  src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java
  src/test/java/com/vincent/domain/feedback/controller/FeedbackControllerTest.java
  src/test/java/com/vincent/domain/member/controller/MemberControllerTest.java
Labels: :sparkles: Feature
