Repository VINCENT-ARCHIVE/Vincent-Server, pull requests merged in 2024-08, with the labels that each got.

#39 Feat/28 빌딩 검색 api
  config/checkstyle.xml
  config/formatter.xml
  src/main/java/com/vincent/apipayload/ApiResponse.java
  src/main/java/com/vincent/apipayload/status/ErrorStatus.java
  src/main/java/com/vincent/apipayload/status/SuccessStatus.java
  src/main/java/com/vincent/config/security/SecurityConfig.java
  src/main/java/com/vincent/config/security/filter/BlackListFilter.java
  src/main/java/com/vincent/config/security/filter/JwtFilter.java
  src/main/java/com/vincent/config/security/handler/JwtAccessDeniedHandler.java
  src/main/java/com/vincent/config/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/vincent/config/security/provider/JwtProvider.java
  src/main/java/com/vincent/config/swagger/SwaggerConfig.java
  src/main/java/com/vincent/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/vincent/domain/building/controller/BuildingController.java
  src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java
  src/main/java/com/vincent/domain/building/converter/BuildingConverter.java
  src/main/java/com/vincent/domain/building/repository/BuildingRepository.java
  src/main/java/com/vincent/domain/building/service/BuildingService.java
  src/main/java/com/vincent/domain/feedback/controller/FeedbackController.java
  src/main/java/com/vincent/domain/feedback/service/FeedbackService.java
  src/main/java/com/vincent/domain/member/controller/MemberController.java
  src/main/java/com/vincent/domain/member/converter/MemberConverter.java
  src/main/java/com/vincent/domain/member/service/MemberService.java
  src/main/java/com/vincent/redis/service/RedisService.java
  src/test/java/com/vincent/domain/bookmark/controller/BookmarkControllerTest.java
  src/test/java/com/vincent/domain/bookmark/controller/BuildingControllerTest.java
  src/test/java/com/vincent/domain/bookmark/controller/FeedbackControllerTest.java
  src/test/java/com/vincent/domain/bookmark/service/BookmarkServiceTest.java
  src/test/java/com/vincent/domain/bookmark/service/BuildingServiceTest.java
  src/test/java/com/vincent/domain/bookmark/service/FeedbackServiceTest.java
Labels: :sparkles: Feature

#43 :sparkles: 건물 등록 API
  build.gradle
  src/main/java/com/vincent/config/aws/s3/S3Config.java
  src/main/java/com/vincent/config/aws/s3/S3Service.java
  src/main/java/com/vincent/config/redis/entity/BlackList.java
  src/main/java/com/vincent/config/redis/entity/RefreshToken.java
  src/main/java/com/vincent/config/redis/repository/RefreshTokenRepository.java
  src/main/java/com/vincent/config/redis/service/RedisService.java
  src/main/java/com/vincent/config/security/SecurityConfig.java
  src/main/java/com/vincent/config/security/filter/BlackListFilter.java
  src/main/java/com/vincent/config/security/filter/JwtFilter.java
  src/main/java/com/vincent/config/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/vincent/config/security/provider/JwtProvider.java
  src/main/java/com/vincent/domain/building/controller/BuildingController.java
  src/main/java/com/vincent/domain/building/controller/dto/BuildingRequestDto.java
  src/main/java/com/vincent/domain/building/converter/BuildingConverter.java
  src/main/java/com/vincent/domain/building/entity/Building.java
  src/main/java/com/vincent/domain/building/service/BuildingService.java
  src/main/java/com/vincent/domain/member/service/MemberService.java
  src/main/java/com/vincent/exception/ExceptionAdvice.java
  src/main/resources/application.yml
  src/test/java/com/vincent/domain/bookmark/service/BuildingServiceTest.java
  src/test/java/com/vincent/domain/member/service/MemberServiceTest.java
Labels: :sparkles: Feature

#45 층 등록 API
  src/main/java/com/vincent/config/aws/s3/S3Service.java
  src/main/java/com/vincent/domain/building/controller/BuildingController.java
  src/main/java/com/vincent/domain/building/controller/dto/BuildingRequestDto.java
  src/main/java/com/vincent/domain/building/entity/Floor.java
  src/main/java/com/vincent/domain/building/repository/FloorRepository.java
  src/main/java/com/vincent/domain/building/service/BuildingService.java
  src/test/java/com/vincent/domain/bookmark/service/BuildingServiceTest.java
Labels: :sparkles: Feature

#49 Fix/48 찜한 북마크 조회하기 api의 ResponseDto, Converter 수정
  src/main/java/com/vincent/domain/bookmark/controller/dto/BookmarkResponseDto.java
  src/main/java/com/vincent/domain/bookmark/converter/BookmarkConverter.java
  src/test/java/com/vincent/domain/bookmark/controller/BookmarkControllerTest.java
Labels: :hammer: fix

#51 Feat/38 개별 콘센트 조회 api
  src/main/java/com/vincent/domain/bookmark/controller/BookmarkController.java
  src/main/java/com/vincent/domain/socket/controller/SocketController.java
  src/main/java/com/vincent/domain/socket/controller/dto/SocketResponseDto.java
  src/main/java/com/vincent/domain/socket/converter/SocketConverter.java
  src/main/java/com/vincent/domain/socket/service/SocketService.java
  src/test/java/com/vincent/domain/bookmark/controller/SocketControllerTest.java
  src/test/java/com/vincent/domain/bookmark/service/SocketServiceTest.java
Labels: :sparkles: Feature

#55 :hammer: S3 재설정 및 테스트 코드 작성
  src/main/java/com/vincent/apipayload/status/ErrorStatus.java
  src/main/java/com/vincent/config/aws/s3/S3Service.java
  src/test/java/com/vincent/aws/S3ServiceTest.java
Labels: :hammer: fix, :sparkles: Feature

#56 Feat/53 공간 등록 api
  src/main/java/com/vincent/apipayload/status/ErrorStatus.java
  src/main/java/com/vincent/config/aws/s3/S3Service.java
  src/main/java/com/vincent/domain/building/controller/BuildingController.java
  src/main/java/com/vincent/domain/building/entity/Space.java
  src/main/java/com/vincent/domain/building/repository/SpaceRepository.java
  src/main/java/com/vincent/domain/building/service/BuildingService.java
  src/test/java/com/vincent/domain/bookmark/controller/BuildingControllerTest.java
  src/test/java/com/vincent/domain/bookmark/service/BuildingServiceTest.java
Labels: :sparkles: Feature

#58 [Feat/57] 모니터링 시스템 구축
  .gitignore
  build.gradle
  monitoring/docker-compose.yml
  monitoring/prometheus.yml
  src/main/java/com/vincent/config/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: :sparkles: Feature

#52 Feat/50 층 조회 api
  src/main/java/com/vincent/domain/building/controller/BuildingController.java
  src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java
  src/main/java/com/vincent/domain/building/converter/BuildingConverter.java
  src/main/java/com/vincent/domain/building/entity/Space.java
  src/main/java/com/vincent/domain/building/repository/FloorRepository.java
  src/main/java/com/vincent/domain/building/repository/SpaceRepository.java
  src/main/java/com/vincent/domain/building/service/BuildingService.java
  src/test/java/com/vincent/domain/bookmark/controller/BuildingControllerTest.java
  src/test/java/com/vincent/domain/bookmark/service/BuildingServiceTest.java
Labels: :sparkles: Feature

#60 [Feat/59] 로깅 설정
  .gitignore
  src/main/java/com/vincent/logging/LoggingFilter.java
  src/main/java/com/vincent/logging/RequestLogInfo.java
  src/main/java/com/vincent/logging/RequestWrapper.java
  src/main/java/com/vincent/logging/ResponseLogInfo.java
  src/main/java/com/vincent/logging/ResponseWrapper.java
  src/main/resources/logback.xml
Labels: :sparkles: Feature

#65 [Bug/64] 빌딩 등록 오류 수정
  src/main/java/com/vincent/domain/building/controller/BuildingController.java
  src/main/java/com/vincent/exception/ExceptionAdvice.java
  src/main/java/com/vincent/logging/LoggingFilter.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
Labels: :bug: bug

#67 Feat/61 층 소켓 조회 api
  src/main/java/com/vincent/domain/socket/controller/SocketController.java
  src/main/java/com/vincent/domain/socket/controller/dto/SocketResponseDto.java
  src/main/java/com/vincent/domain/socket/converter/SocketConverter.java
  src/main/java/com/vincent/domain/socket/repository/SocketRepository.java
  src/main/java/com/vincent/domain/socket/service/SocketService.java
  src/test/java/com/vincent/domain/bookmark/service/SocketServiceTest.java
  src/test/java/com/vincent/domain/building/controller/BuildingControllerTest.java
  src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java
  src/test/java/com/vincent/domain/feedback/controller/FeedbackControllerTest.java
  src/test/java/com/vincent/domain/feedback/service/FeedbackServiceTest.java
  src/test/java/com/vincent/domain/socket/controller/SocketControllerTest.java
  src/test/java/com/vincent/domain/socket/service/SocketServiceTest.java
Labels: :sparkles: Feature

#70 CI/CD 파이프라인 구축
  .github/workflows/deploy.yml
  Dockerfile
  docker-compose.yml
  src/main/resources/application.yml
  src/test/java/com/vincent/ApplicationTests.java
Labels: :earth_africa: ci

#68 Feat/47 소켓 등록 api
  src/main/java/com/vincent/apipayload/status/ErrorStatus.java
  src/main/java/com/vincent/config/aws/s3/S3Service.java
  src/main/java/com/vincent/domain/building/controller/BuildingController.java
  src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java
  src/main/java/com/vincent/domain/building/converter/BuildingConverter.java
  src/main/java/com/vincent/domain/building/entity/Space.java
  src/main/java/com/vincent/domain/building/service/BuildingService.java
  src/main/java/com/vincent/domain/socket/controller/dto/SocketResponseDto.java
  src/main/java/com/vincent/domain/socket/converter/SocketConverter.java
  src/main/java/com/vincent/domain/socket/entity/Socket.java
  src/test/java/com/vincent/domain/building/controller/BuildingControllerTest.java
  src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java
  src/test/java/com/vincent/domain/socket/controller/SocketControllerTest.java
Labels: :sparkles: Feature

#77 [Bug/76] Hikaripool Thread starvation 오류
  src/main/resources/application.yml
Labels: :bug: bug

#78 Fix/73 로직 변경
  src/main/java/com/vincent/domain/building/controller/BuildingController.java
  src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java
  src/main/java/com/vincent/domain/building/converter/BuildingConverter.java
  src/main/java/com/vincent/domain/building/entity/Space.java
  src/main/java/com/vincent/domain/building/repository/FloorRepository.java
  src/main/java/com/vincent/domain/building/repository/SpaceRepository.java
  src/main/java/com/vincent/domain/building/service/BuildingService.java
  src/main/java/com/vincent/domain/socket/controller/dto/SocketResponseDto.java
  src/main/java/com/vincent/domain/socket/converter/SocketConverter.java
  src/main/java/com/vincent/domain/socket/entity/Socket.java
  src/test/java/com/vincent/domain/building/controller/BuildingControllerTest.java
  src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java
Labels: :hammer: fix

#79 [Fix/75] yml 수정
  .github/workflows/deploy.yml
  .github/workflows/test.yml
  Dockerfile
  src/main/java/com/vincent/domain/bookmark/service/BookmarkService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: :hammer: fix
