Repository VINCENT-ARCHIVE/Vincent-Server, pull requests merged in 2024-12, with the labels that each got.

#180 :recycle: 피드백 테스트 코드 모킹 제거
  src/test/java/com/vincent/domain/feedback/TestFeedbackRepository.java
  src/test/java/com/vincent/domain/feedback/service/FeedbackServiceTest.java
  src/test/java/com/vincent/domain/feedback/service/data/FeedbackDataServiceTest.java
Labels: :recycle: refactor

#182 :sparkles: MAU 로직 구현
  src/main/java/com/vincent/logs/LogProcessor.java
  src/main/java/com/vincent/logs/LogScheduler.java
  src/main/java/com/vincent/logs/LogService.java
  src/main/java/com/vincent/logs/repository/MonthlyActiveUsersRepository.java
Labels: :sparkles: Feature

#185 [Fix/176] 층 콘센트 조회 성능 개선 & 소켓 테스트 코드 모킹 제거
  src/main/java/com/vincent/domain/socket/repository/customsocket/CustomSocketRepository.java
  src/main/java/com/vincent/domain/socket/repository/customsocket/CustomSocketRepositoryImpl.java
  src/main/java/com/vincent/domain/socket/service/SocketService.java
  src/main/java/com/vincent/domain/socket/service/data/SocketDataService.java
  src/test/java/com/vincent/domain/building/TestBuildingRepository.java
  src/test/java/com/vincent/domain/building/TestFloorRepository.java
  src/test/java/com/vincent/domain/building/TestSpaceRepository.java
  src/test/java/com/vincent/domain/socket/TestSocketRepository.java
  src/test/java/com/vincent/domain/socket/service/SocketServiceTest.java
  src/test/java/com/vincent/domain/socket/service/data/SocketDataServiceTest.java
Labels: :hammer: fix, :recycle: refactor

#187 [Refactor/186] Socket 테스트 코드 수정 및 로직 수정
  src/main/java/com/vincent/domain/socket/converter/SocketConverter.java
  src/main/java/com/vincent/domain/socket/repository/SocketRepository.java
  src/main/java/com/vincent/domain/socket/repository/customsocket/CustomSocketRepository.java
  src/main/java/com/vincent/domain/socket/repository/customsocket/CustomSocketRepositoryImpl.java
  src/main/java/com/vincent/domain/socket/service/SocketService.java
  src/main/java/com/vincent/domain/socket/service/data/SocketDataService.java
  src/test/java/com/vincent/domain/socket/TestSocketRepository.java
  src/test/java/com/vincent/domain/socket/controller/SocketControllerTest.java
  src/test/java/com/vincent/domain/socket/service/SocketServiceTest.java
  src/test/java/com/vincent/domain/socket/service/data/SocketDataServiceTest.java
Labels: :hammer: fix, :recycle: refactor
