Repository VINCENT-ARCHIVE/Vincent-Server, pull requests merged in 2024-10, with the labels that each got.

#109 :hammer: 로그 수집 api 수정
  .gitignore
  src/main/java/com/vincent/logs/LogConfig.java
  src/main/java/com/vincent/logs/LogProcessor.java
  src/main/java/com/vincent/logs/LogScheduler.java
  src/main/java/com/vincent/logs/LogService.java
  src/main/java/com/vincent/logs/entity/DailyActiveUsers.java
  src/main/java/com/vincent/logs/entity/MonthlyActiveUsers.java
  src/main/java/com/vincent/logs/repository/DailyActiveUsersRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/logback.xml
Labels: :hammer: fix

#114 [Hotfix/113] :hammer: BookmarkService -> delete 함수 수정
  src/main/java/com/vincent/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/vincent/domain/bookmark/service/BookmarkService.java
  src/test/java/com/vincent/domain/bookmark/service/BookmarkServiceTest.java
  src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java
Labels: :fire: hotfix

#116 [Fix/115] :hammer: 피드백 생성 시 생성시간 설정, request 중복 제거
  src/main/java/com/vincent/domain/feedback/controller/FeedbackController.java
  src/main/java/com/vincent/domain/feedback/entity/Feedback.java
Labels: :hammer: fix

#117 Fix/105 공간 엔티티의 이미지 필드 제거
  src/main/java/com/vincent/domain/building/controller/BuildingController.java
  src/main/java/com/vincent/domain/building/entity/Space.java
  src/main/java/com/vincent/domain/building/service/BuildingService.java
  src/test/java/com/vincent/domain/building/controller/BuildingControllerTest.java
  src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java
Labels: :hammer: fix

#118 [Fix/113] :hammer: 북마크 취소 api 수정
  src/main/java/com/vincent/apipayload/status/ErrorStatus.java
  src/main/java/com/vincent/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/com/vincent/domain/bookmark/service/BookmarkService.java
  src/main/java/com/vincent/domain/bookmark/service/data/BookmarkDataService.java
  src/test/java/com/vincent/domain/bookmark/service/BookmarkServiceTest.java
  src/test/java/com/vincent/domain/bookmark/service/data/BookmarkDataServiceTest.java
Labels: :hammer: fix

#120 [Fix/119] :hammer: 피드백 생성 api 오류
  src/main/java/com/vincent/domain/feedback/controller/FeedbackController.java
  src/main/java/com/vincent/domain/feedback/entity/Feedback.java
Labels: :hammer: fix

#127 Hotfix/124 층 정보 조회 시 소켓이 존재하는 층 리스트 추가
  src/main/java/com/vincent/domain/building/controller/BuildingController.java
  src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java
  src/main/java/com/vincent/domain/building/converter/BuildingConverter.java
  src/main/java/com/vincent/domain/building/repository/customfloor/CustomFloorRepository.java
  src/main/java/com/vincent/domain/building/repository/customfloor/CustomFloorRepositoryImpl.java
  src/main/java/com/vincent/domain/building/service/BuildingService.java
  src/main/java/com/vincent/domain/building/service/data/FloorDataService.java
  src/test/java/com/vincent/domain/building/controller/BuildingControllerTest.java
  src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java
  src/test/java/com/vincent/domain/building/service/data/FloorDataServiceTest.java
Labels: :fire: hotfix

#128 :hammer: 파이프라인 수정
  .github/workflows/deploy.yml
  docker-compose.yml
  src/main/java/com/vincent/config/swagger/SwaggerConfig.java
Labels: :earth_africa: ci

#131 :hammer: 빌딩 검색 api 수정
  src/main/java/com/vincent/domain/building/controller/BuildingController.java
  src/main/java/com/vincent/domain/building/repository/custombuilding/CustomBuildingRepositoryImpl.java
Labels: :hammer: fix

#133 [Fix/123] 건물 정보 조회api 수정
  src/main/java/com/vincent/domain/building/controller/BuildingController.java
  src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java
  src/main/java/com/vincent/domain/building/converter/BuildingConverter.java
  src/main/java/com/vincent/domain/building/repository/FloorRepository.java
  src/main/java/com/vincent/domain/building/repository/customfloor/CustomFloorRepository.java
  src/main/java/com/vincent/domain/building/repository/customfloor/CustomFloorRepositoryImpl.java
  src/main/java/com/vincent/domain/building/service/BuildingService.java
  src/main/java/com/vincent/domain/building/service/data/FloorDataService.java
  src/test/java/com/vincent/domain/building/controller/BuildingControllerTest.java
  src/test/java/com/vincent/domain/building/service/BuildingServiceTest.java
  src/test/java/com/vincent/domain/building/service/data/FloorDataServiceTest.java
Labels: :hammer: fix

#143 [Fix/142] :hammer: 층 콘센트 조회 @jsonProperty 추가, @jsonPropertyOrder로 순서 고정
  src/main/java/com/vincent/domain/building/controller/dto/BuildingResponseDto.java
  src/main/java/com/vincent/domain/socket/controller/dto/SocketResponseDto.java
Labels: :hammer: fix

#146 :hammer: docker-compose 파일 서버에 복사
  .github/workflows/deploy.yml
Labels: :hammer: fix, :earth_africa: ci

#148 :hammer: git action script 분리
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  docker-compose.dev.yml
  docker-compose.prod.yml
Labels: :earth_africa: ci

#154 :hammer: docker-compose 수정
  docker-compose.dev.yml
  docker-compose.prod.yml
Labels: :earth_africa: ci

#157 :sparkles: 애플 로그인 추가
  src/main/java/com/vincent/config/security/provider/JwtProvider.java
  src/main/java/com/vincent/domain/member/controller/MemberController.java
  src/main/java/com/vincent/domain/member/controller/dto/MemberRequestDto.java
  src/main/java/com/vincent/domain/member/entity/Member.java
  src/main/java/com/vincent/domain/member/entity/enums/SocialType.java
  src/main/java/com/vincent/domain/member/repository/MemberRepository.java
  src/main/java/com/vincent/domain/member/service/MemberService.java
  src/main/java/com/vincent/domain/member/service/data/MemberDataService.java
  src/test/java/com/vincent/domain/member/controller/MemberControllerTest.java
  src/test/java/com/vincent/domain/member/service/MemberServiceTest.java
  src/test/java/com/vincent/domain/member/service/data/MemberDataServiceTest.java
Labels: :sparkles: Feature

#160 :earth_africa: git action 수정
  .github/workflows/deploy-dev.yml
  Dockerfile
  docker-compose.yml
Labels: :earth_africa: ci

#163 :hammer: git action .env 수정
  .github/workflows/deploy-dev.yml
  src/main/java/com/vincent/config/swagger/SwaggerConfig.java
Labels: :hammer: fix
