Repository VINCENT-ARCHIVE/Vincent-Server, pull requests merged in 2025-01, with the labels that each got.

#190 [Fix/189] MAU 로직 수정
  src/main/java/com/vincent/logs/LogService.java
Labels: :hammer: fix

#197 [Fix/196] 주변 건물 조회 범위 변수 재확대
  src/main/java/com/vincent/domain/building/service/data/BuildingDataService.java
  src/test/java/com/vincent/domain/building/service/data/BuildingDataServiceTest.java
Labels: :hammer: fix

#198 [Feat] Iot 장치 등록
  src/main/java/com/vincent/domain/iot/controller/IotController.java
  src/main/java/com/vincent/domain/iot/controller/converter/IotConverter.java
  src/main/java/com/vincent/domain/iot/controller/dto/IotRequestDto.java
  src/main/java/com/vincent/domain/iot/entity/Iot.java
  src/main/java/com/vincent/domain/iot/repository/IotRepository.java
  src/main/java/com/vincent/domain/iot/service/IotService.java
  src/main/java/com/vincent/domain/iot/service/data/IotDataService.java
  src/main/java/com/vincent/domain/socket/repository/SocketRepository.java
  src/main/java/com/vincent/domain/socket/service/data/SocketDataService.java
  src/test/java/com/vincent/domain/iot/TestIotRepository.java
  src/test/java/com/vincent/domain/iot/service/IotServiceTest.java
  src/test/java/com/vincent/domain/iot/service/data/IotDataServiceTest.java
  src/test/java/com/vincent/domain/socket/TestSocketRepository.java
  src/test/java/com/vincent/domain/socket/service/data/SocketDataServiceTest.java
Labels: :sparkles: Feature

#200 :hammer: [Fix/193] 층 콘센트 조회, 개별 콘센트 조회 api에 소켓 사용 여부 필드 추가
  src/main/java/com/vincent/domain/building/service/BuildingService.java
  src/main/java/com/vincent/domain/socket/controller/SocketController.java
  src/main/java/com/vincent/domain/socket/controller/dto/SocketResponseDto.java
  src/main/java/com/vincent/domain/socket/converter/SocketConverter.java
  src/main/java/com/vincent/domain/socket/entity/Socket.java
Labels: :hammer: fix

#201 [Feat/194] IoT기기의 0/1 값을 받아서 소켓의 사용 여부 필드를 변경하는 api 생성
  src/main/java/com/vincent/apipayload/status/ErrorStatus.java
  src/main/java/com/vincent/config/redis/service/RedisService.java
  src/main/java/com/vincent/domain/iot/controller/IotController.java
  src/main/java/com/vincent/domain/iot/controller/converter/IotConverter.java
  src/main/java/com/vincent/domain/iot/controller/dto/IotResponseDto.java
  src/main/java/com/vincent/domain/iot/repository/IotRepository.java
  src/main/java/com/vincent/domain/iot/service/IotService.java
  src/main/java/com/vincent/domain/iot/service/data/IotDataService.java
  src/main/java/com/vincent/domain/socket/entity/Socket.java
  src/test/java/com/vincent/config/redis/service/RedisServiceTest.java
  src/test/java/com/vincent/config/redis/service/TestRedisService.java
  src/test/java/com/vincent/config/redis/service/TestRedisTemplate.java
  src/test/java/com/vincent/domain/iot/TestIotRepository.java
  src/test/java/com/vincent/domain/iot/service/IotServiceTest.java
  src/test/java/com/vincent/domain/iot/service/data/IotDataServiceTest.java
Labels: :sparkles: Feature

#207 [Fix] 소켓 상태 변경 로직 수정
  src/main/java/com/vincent/config/redis/RedisConfig.java
  src/main/java/com/vincent/config/redis/service/RedisKeyExpirationListener.java
  src/main/java/com/vincent/config/redis/service/RedisService.java
  src/main/java/com/vincent/domain/iot/controller/IotController.java
  src/main/java/com/vincent/domain/iot/controller/converter/IotConverter.java
  src/main/java/com/vincent/domain/iot/controller/dto/IotResponseDto.java
  src/main/java/com/vincent/domain/iot/entity/Iot.java
  src/main/java/com/vincent/domain/iot/service/IotService.java
  src/main/java/com/vincent/domain/socket/entity/Socket.java
  src/test/java/com/vincent/config/redis/service/TestRedisTemplate.java
  src/test/java/com/vincent/domain/iot/TestIotRepository.java
  src/test/java/com/vincent/domain/iot/service/IotServiceTest.java
Labels: :hammer: fix

#208 :hammer: iot가 전달한 값에 따라 1 -> 사용중, 0 -> 10분 후 사용 없음으로 변경하는 로직
  src/main/java/com/vincent/config/redis/service/RedisKeyExpirationListener.java
  src/main/java/com/vincent/config/redis/service/RedisService.java
  src/main/java/com/vincent/config/security/SecurityConfig.java
  src/main/java/com/vincent/domain/iot/controller/IotController.java
  src/main/java/com/vincent/domain/iot/entity/Iot.java
  src/main/java/com/vincent/domain/iot/entity/enums/MotionStatus.java
  src/main/java/com/vincent/domain/iot/service/IotService.java
  src/test/java/com/vincent/config/redis/service/RedisServiceTest.java
  src/test/java/com/vincent/domain/iot/service/IotServiceTest.java
Labels: :hammer: fix

#212 :recycle: DDD 원칙 적용하여 IoT 상태 관리 로직 개선
  src/main/java/com/vincent/domain/iot/entity/Iot.java
  src/main/java/com/vincent/domain/iot/service/IotService.java
Labels: :recycle: refactor
